### ISSUE TITLE
考慮增加行距，以提高大段發言易讀性

### ISSUE THREAD

**Issue by venevchao** [audreyt/archive.tw#1]
目前 line-height 預設1.421em, 閱讀大段發言時略感吃力（圖1）
考量中文易讀性並兼顧 mobile 內容密度，是否提高為 1.6em（圖2）

以下引自 **傳統編輯對部落格新手的寫作建議：一個呼籲 by 老貓**
https://plus.google.com/+venevchao/posts/9t7FRhQdZ4b

"網路閱讀因為眼睛的距離比讀紙張書更遠，理論上行距應該更寬才對，合理的行距需要配合行的長度調節，但至少不應該少於字級大小的 50％（如果你可以設定模版的話，請把正文行距設定為 line-height: 1.5 以上。以老貓學出版為例，我的內文行距是 line-height: 1.7 ）。

行距的重要性甚至超過字體大小，而適合英文的模版，行距通常不適合中文閱讀，所以這個應該列為一定要修改的項目才好。"

<img width="1440" alt="screen shot 2015-09-14 at 04 58 00" src="https://cloud.githubusercontent.com/assets/5195513/9839034/d77230d6-5a9f-11e5-88da-eacbed0c11cf.png">
<img width="1440" alt="screen shot 2015-09-14 at 04 58 33" src="https://cloud.githubusercontent.com/assets/5195513/9839035/d776b624-5a9f-11e5-8782-e4521a8a4c3e.png">

**Comment by audreyt** [comment]
感謝建議，已換成 1.6em （窄螢幕） / 1.7em （寬螢幕），shift-reload 即可。

**Comment by audreyt** [comment]
在 @c9s 提醒下換成了黑體，`2em`

**Comment by c9s** [comment]
👍👍👍👍👍👍
